### ISSUE TITLE
failed to solve: executor failed running [/bin/sh -c apk add openjdk17]: exit code: 1

### ISSUE THREAD

**Issue by stitchshaw** [pushpankar/LLMCurator.io#1]
Hi! I met this issue while running "docker-compose up"
![image](https://github.com/pushpankar/LLMCurator.io/assets/84279893/c41f5389-48a6-47bd-a48b-fcc39007e375)

**Comment by pushpankar** [comment]
I can see that the connection was aborted during jvm download. It might have occurred due internet issue. Can you retry with faster and more stable internet?
